In [26]:
# Step 1: Setup
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [20]:
import pandas as pd
import os
from tqdm import tqdm

# Paths
data_dir = "/content/drive/MyDrive/DTSC 5082 Datasets"
discharge_path = os.path.join(data_dir, "cleaned_discharge.csv")
mimic_path = os.path.join(data_dir, "mimic-iv-bhc.csv")

# Load datasets
discharge_df = pd.read_csv(discharge_path)
mimic_df = pd.read_csv(mimic_path)
pd.set_option('display.max_colwidth', None)

In [21]:
discharge_df.head(1)

          note_id  subject_id   hadm_id note_type  note_seq  \
0  10000032-DS-21    10000032  22595853        DS        21

             charttime            storetime  \
0  2180-05-07 00:00:00  2180-05-09 15:26:00

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    text
0  Name: ** Unit No: ** Admission Date: ** Discharge Date: ** Date of Birth: ** Sex: F Service: MEDICINE Allergies: No Known Allergies / Adverse Drug Reactions Attending: ** Chief Complaint: Worsening ABD distension and pain Major Surgical or Invasive Procedure: Paracentesis History of Present Illness: ** Hepatitis C Virus cirrhosis c/b ascites, hiv on Antiretroviral Therapy,History OfIVDU, Chronic Obstructive Pulmonary Disease, bioplar, Post-Traumatic Stress Disorder, presented from Left EyeH ED with worsening abd distension over past week. Patientreports self-discontinuing lasix and spirnolactone ** weeks ago, because she feels like they don't do anything and that she doesn't want to put more chemicals in her. She does not follow Na-restricted diets. In the past week, she notes that she has been having worsening abd distension and discomfort. She denies ** edema, or Shortness of Breath, or orthopnea. She denies f/c/n/v, d/c, dysuria. She had food poisoning a week ago from eating stale cake (n/v 20 min after food ingestion), which resolved the same day. She denies other recent illness or sick contacts. She notes that she has been noticing gum bleeding while brushing her teeth in recent weeks. she denies easy bruising, melena, BRBlood PressureR, hemetesis, hemoptysis, or hematuria. Because of her abd pain, she went to Left EyeH ED and was transferred to ** for further care. Per ED report, pt has brief period of confusion - she did not recall the ultrasound or bloodwork at osh. She denies recent drug use or alcohol use. She denies feeling confused, but reports that she is forgetful at times. In the ED, initial vitals were 98.4 70 106/63 16 97%RA Labs notable for Alanine Aminotransferase/Aspartate Aminotransferase/AP ** ** : ** , Tbili1.6, White Blood Cell Count 5K, platelet 77, International Normalized Ratio 1.6 Past Medical History: 1. Hepatitis C Virus Cirrhosis 2. No history of abnormal Pap smears. 3. She had calcification in her breast, which was removed previously and per patient not, it was benign. 4. For Human Immunodeficiency Virus disease, she is being followed by Dr. ** Dr. ** . 5. Chronic Obstructive Pulmonary Disease 6. Past history of smoking. 7. She also had a skin lesion, which was biopsied and showed skin cancer per patient report and is scheduled for a complete removal of the skin lesion in ** of this year. 8. She also had another lesion in her forehead with purple discoloration. It was biopsied to exclude the possibility of ** 's sarcoma, the results is pending. 9. A 15 mm hypoechoic lesion on her ultrasound on ** and is being monitored by an Magnetic Resonance Imaging. 10. History of dysplasia of anus in ** . 11. Bipolar affective disorder, currently manic, mild, and Post-Traumatic Stress Disorder. 12. History of cocaine and heroin use. Social History: ** Family History: She a total of five siblings, but she is not talking to most of them. She only has one brother that she is in touch with and lives in ** . She is not aware of any known GI or liver disease in her family. Her last alcohol consumption was one drink two months ago. No regular alcohol consumption. Last drug use ** years ago. She quit smoking a couple of years ago. Physical Exam: VS: 98.1 107/61 78 18 97RA General: in NAD HEENT: Computed TomographyAB, anicteric sclera, OP clear Neck: supple, no LAD CV: Respiratory RateR,S1S2, no m/r/g Lungs: Computed TomographyAb, prolonged expiratory phase, no w/r/r Abdomen: distended, mild diffuse tenderness, +flank dullness, cannot percuss liver/spleen edge ** distension GU: no foley Ext: wwp, no c/e/e, + clubbing Neuro: AAO3, converse normally, able to recall 3 times after 5 minutes, CN II-XII intact Discharge: PHYSICAL EXAMINATION: VS: 98 105/70 95 General: in NAD HEENT: anicteric sclera, OP clear Neck: supple, no LAD CV: Respiratory RateR,S1S2, no m/r/g Lungs: Computed TomographyAb, prolonged expiratory phase, no w/r/r Abdomen: distended but improved, TTP in RUQ, GU: no foley Ext: wwp, no c/e/e, + clubbing Neuro: AAO3, CN II-XII intact Pertinent Results: ** 10:25PM GLUCLeft EyeE-109* UREA N-25* CREAT-0.3* SRight EyeIUM-138 POTASSIUM-3.4 CHLOperating RoomInfectious DiseaseE-105 TOTAL CO2-27 ANION GAP-9 ** 10:25PM estGFR-Using this ** 10:25PM Alanine Aminotransferase(SGPT)-100* Aspartate Aminotransferase(SGOT)-114* ALK PHLeft Eye-114* TOT BILI-1.6* ** 10:25PM LIPASE-77* ** 10:25PM ALBUMIN-3.3* ** 10:25PM White Blood Cell Count-5.0 Red Blood Cell Count-4.29 HGB-14.3 Hematocrit-42.6 MCV-99* MCH-33.3* MCHC-33.5 RDW-15.7* ** 10:25PM NEUTS-70.3* LYMPAt Bedtime-16.5* MONLeft Eye-8.1 ELeft Eye-4.2* BASLeft Eye-0.8 ** 10:25PM Platelet Count CBoth EyesNT-71* ** 10:25PM ** Partial Thromboplastin Time-30.9 ** ** 10:25PM ** . Chest X-Ray: No acute cardiopulmonary process. U/S: 1. Nodular appearance of the liver compatible with cirrhosis. Signs of portal hypertension including small amount of ascites and splenomegaly. 2. Cholelithiasis. 3. Patent portal veins with normal hepatopetal flow. Diagnostic para attempted in the ED, unsuccessful. On the floor, pt c/o abd distension and discomfort. Brief Hospital Course: ** Hepatitis C Virus cirrhosis c/b ascites, hiv on Antiretroviral Therapy,History OfIVDU, Chronic Obstructive Pulmonary Disease, bioplar, Post-Traumatic Stress Disorder, presented from Left EyeH ED with worsening abd distension over past week and confusion. Ascites - p/w worsening abd distension and discomfort for last week. likely ** portal Hypertension given underlying liver disease, though no ascitic fluid available on night of admission. No signs of heart failure noted on exam. This was ** to med non-compliance and lack of diet restriction. SBlood Pressure negative diuretics: Furosemide 40 mg PO DAILY Spironolactone 50 mg PO DAILY, chosen over the usual 100mg dose d/t K+ of 4.5. Chest X-Ray was wnl, Urinalysis negative, Urine culture blood culture negative. Patientwas losing excess fluid appropriately with stable lytes on the above regimen. Patientwas scheduled with current After Mealshest Pain for ** check upon discharge. Patientwas scheduled for new After Mealshest Pain with Dr. ** at ** and follow up in Liver clinic to schedule outpatient screening Esophagogastroduodenoscopy and ** . Medications on Admission: The Preadmission Medication list is accurate and complete. 1. Furosemide 20 mg PO DAILY 2. Spironolactone 50 mg PO DAILY 3. Albuterol Inhaler 2 PUFF IH Q4H:Per RectumN wheezing, Shortness of Breath 4. Raltegravir 400 mg PO BInfectious Disease 5. Emtricitabine-Tenofovir (Truvada) 1 TAB PO DAILY 6. Nicotine Patch 14 mg TD DAILY 7. Ipratropium Bromide Neb 1 NEB IH Q6H Shortness of Breath Discharge Medications: 1. Albuterol Inhaler 2 PUFF IH Q4H:Per RectumN wheezing, Shortness of Breath 2. Emtricitabine-Tenofovir (Truvada) 1 TAB PO DAILY 3. Furosemide 40 mg PO DAILY RX *furosemide 40 mg 1 tablet(s) by mouth Daily Disp *30 Tablet Refills:*3 4. Ipratropium Bromide Neb 1 NEB IH Q6H Shortness of Breath 5. Nicotine Patch 14 mg TD DAILY 6. Raltegravir 400 mg PO BInfectious Disease 7. Spironolactone 50 mg PO DAILY 8. Acetaminophen 500 mg PO Q6H:Per RectumN pain Discharge Disposition: Home Discharge Diagnosis: Ascites from Portal Hypertension Discharge Condition: Mental Status: Clear and coherent. Level of Consciousness: Alert and interactive. Activity Status: Ambulatory - Independent. Discharge Instructions: Dear Ms. ** , It was a pleasure taking care of you You came to us with stomach pain and worsening distension. While you were here we did a paracentesis to remove 1.5L of fluid from your belly. We also placed you on you 40 mg of Furosemideand 50 mg of Spironolactoneto help you urinate the excess fluid still in your belly. As we discussed, everyone has a different dose of lasix required to make them urinate and it's likely that you weren't taking a high enough dose. Please take these medications daily to keep excess fluid off and eat a low salt diet. You will follow up with Dr. ** in liver clinic and from there have your colonoscopy and Esophagogastroduodenoscopy scheduled. Of course, we are always here if you need us. We wish you all the best Your ** Team. Followup Instructions: **

In [22]:
mimic_df.head(1)

          note_id  \
0  10000032-DS-21

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                input  \
0  <SEX> F <SERVICE> MEDICINE <ALLERGIES> No Known Allergies / Adverse Drug Reactions <ATTENDING> ___ <CHIEF COMPLAINT> Worsening ABD distension and pain <MAJOR SURGICAL OR INVASIVE PROCEDURE> Paracentesis <HISTORY OF PRESENT ILLNESS> ___ HCV cirrhosis c/b ascites, hiv on ART, h/o IVDU, COPD, bioplar, PTSD, presented from OSH ED with worsening abd distension over past week. Pt reports self-discontinuing lasix and spirnolactone ___ weeks ago, because she feels like "they don't do anything" and that she "doesn't want to put more chemicals in her." She does not follow Na-restricted diets. In the past week, she notes that she has been having worsening abd distension and discomfort. She denies ___ edema, or SOB, or orthopnea. She denies f/c/n/v, d/c, dysuria. She had food poisoning a week ago from eating stale cake (n/v 20 min after food ingestion), which resolved the same day. She denies other recent illness or sick contacts. She notes that she has been noticing gum bleeding while brushing her teeth in recent weeks. she denies easy bruising, melena, BRBPR, hemetesis, hemoptysis, or hematuria. Because of her abd pain, she went to OSH ED and was transferred to ___ for further care. Per ED report, pt has brief period of confusion - she did not recall the ultrasound or bloodwork at osh. She denies recent drug use or alcohol use. She denies feeling confused, but reports that she is forgetful at times. In the ED, initial vitals were 98.4 70 106/63 16 97%RA Labs notable for ALT/AST/AP ___ ___: ___, Tbili1.6, WBC 5K, platelet 77, INR 1.6 <PAST MEDICAL HISTORY> 1. HCV Cirrhosis 2. No history of abnormal Pap smears. 3. She had calcification in her breast, which was removed previously and per patient not, it was benign. 4. For HIV disease, she is being followed by Dr. ___ Dr. ___. 5. COPD 6. Past history of smoking. 7. She also had a skin lesion, which was biopsied and showed skin cancer per patient report and is scheduled for a complete removal of the skin lesion in ___ of this year. 8. She also had another lesion in her forehead with purple discoloration. It was biopsied to exclude the possibility of ___'s sarcoma, the results is pending. 9. A 15 mm hypoechoic lesion on her ultrasound on ___ and is being monitored by an MRI. 10. History of dysplasia of anus in ___. 11. Bipolar affective disorder, currently manic, mild, and PTSD. 12. History of cocaine and heroin use. <SOCIAL HISTORY> ___ <FAMILY HISTORY> She a total of five siblings, but she is not talking to most of them. She only has one brother that she is in touch with and lives in ___. She is not aware of any known GI or liver disease in her family. Her last alcohol consumption was one drink two months ago. No regular alcohol consumption. Last drug use ___ years ago. She quit smoking a couple of years ago. <PHYSICAL EXAM> VS: 98.1 107/61 78 18 97RA General: in NAD HEENT: CTAB, anicteric sclera, OP clear Neck: supple, no LAD CV: RRR,S1S2, no m/r/g Lungs: CTAb, prolonged expiratory phase, no w/r/r Abdomen: distended, mild diffuse tenderness, +flank dullness, cannot percuss liver/spleen edge ___ distension GU: no foley Ext: wwp, no c/e/e, + clubbing Neuro: AAO3, converse normally, able to recall 3 times after 5 minutes, CN II-XII intact Discharge: PHYSICAL EXAMINATION: VS: 98 105/70 95 General: in NAD HEENT: anicteric sclera, OP clear Neck: supple, no LAD CV: RRR,S1S2, no m/r/g Lungs: CTAb, prolonged expiratory phase, no w/r/r Abdomen: distended but improved, TTP in RUQ, GU: no foley Ext: wwp, no c/e/e, + clubbing Neuro: AAO3, CN II-XII intact <PERTINENT RESULTS> ___ 10: 25PM GLUCOSE-109* UREA N-25* CREAT-0.3* SODIUM-138 POTASSIUM-3.4 CHLORIDE-105 TOTAL CO2-27 ANION GAP-9 ___ 10: 25PM estGFR-Using this ___ 10: 25PM ALT(SGPT)-100* AST(SGOT)-114* ALK PHOS-114* TOT BILI-1.6* ___ 10: 25PM LIPASE-77* ___ 10: 25PM ALBUMIN-3.3* ___ 10: 25PM WBC-5.0# RBC-4.29 HGB-14.3 HCT-42.6 MCV-99* MCH-33.3* MCHC-33.5 RDW-15.7* ___ 10: 25PM NEUTS-70.3* LYMPHS-16.5* MONOS-8.1 EOS-4.2* BASOS-0.8 ___ 10: 25PM PLT COUNT-71* ___ 10: 25PM ___ PTT-30.9 ___ ___ 10: 25PM ___ . CXR: No acute cardiopulmonary process. U/S: 1. Nodular appearance of the liver compatible with cirrhosis. Signs of portal hypertension including small amount of ascites and splenomegaly. 2. Cholelithiasis. 3. Patent portal veins with normal hepatopetal flow. Diagnostic para attempted in the ED, unsuccessful. On the floor, pt c/o abd distension and discomfort. <MEDICATIONS ON ADMISSION> The Preadmission Medication list is accurate and complete. 1. Furosemide 20 mg PO DAILY 2. Spironolactone 50 mg PO DAILY 3. Albuterol Inhaler 2 PUFF IH Q4H: PRN wheezing, SOB 4. Raltegravir 400 mg PO BID 5. Emtricitabine-Tenofovir (Truvada) 1 TAB PO DAILY 6. Nicotine Patch 14 mg TD DAILY 7. Ipratropium Bromide Neb 1 NEB IH Q6H SOB <DISCHARGE MEDICATIONS> 1. Albuterol Inhaler 2 PUFF IH Q4H: PRN wheezing, SOB 2. Emtricitabine-Tenofovir (Truvada) 1 TAB PO DAILY 3. Furosemide 40 mg PO DAILY RX *furosemide 40 mg 1 tablet(s) by mouth Daily Disp #*30 Tablet Refills: *3 4. Ipratropium Bromide Neb 1 NEB IH Q6H SOB 5. Nicotine Patch 14 mg TD DAILY 6. Raltegravir 400 mg PO BID 7. Spironolactone 50 mg PO DAILY 8. Acetaminophen 500 mg PO Q6H: PRN pain <DISCHARGE DISPOSITION> Home <DISCHARGE DIAGNOSIS> Ascites from Portal HTN <DISCHARGE CONDITION> Mental Status: Clear and coherent. Level of Consciousness: Alert and interactive. Activity Status: Ambulatory - Independent. <FOLLOWUP INSTRUCTIONS> ___ <DISCHARGE INSTRUCTIONS> Dear Ms. ___, It was a pleasure taking care of you! You came to us with stomach pain and worsening distension. While you were here we did a paracentesis to remove 1.5L of fluid from your belly. We also placed you on you 40 mg of Lasix and 50 mg of Aldactone to help you urinate the excess fluid still in your belly. As we discussed, everyone has a different dose of lasix required to make them urinate and it's likely that you weren't taking a high enough dose. Please take these medications daily to keep excess fluid off and eat a low salt diet. You will follow up with Dr. ___ in liver clinic and from there have your colonoscopy and EGD scheduled. Of course, we are always here if you need us. We wish you all the best! Your ___ Team.

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            target  \
0  ___ HCV cirrhosis c/b ascites, hiv on ART, h/o IVDU, COPD, bioplar, PTSD, presented from OSH ED with worsening abd distension over past week and confusion. # Ascites - p/w worsening abd distension and discomfort for last week. likely ___ portal HTN given underlying liver disease, though no ascitic fluid available on night of admission. No signs of heart failure noted on exam. This was ___ to med non-compliance and lack of diet restriction. SBP negative diuretics: > Furosemide 40 mg PO DAILY > Spironolactone 50 mg PO DAILY, chosen over the usual 100mg dose d/t K+ of 4.5. CXR was wnl, UA negative, Urine culture blood culture negative. Pt was losing excess fluid appropriately with stable lytes on the above regimen. Pt was scheduled with current PCP for ___ check upon discharge. Pt was scheduled for new PCP with Dr. ___ at ___ and follow up in Liver clinic to schedule outpatient screening EGD and ___.

   input_tokens  target_tokens
0          1946            231

In [23]:
# Take first 1000 rows
subset_df = discharge_df.iloc[:1000].copy()

In [24]:
# Step 2: Install and Load T5
!pip install -q transformers evaluate bert_score

In [25]:
import torch
from transformers import T5Tokenizer, T5ForConditionalGeneration

device = "cuda" if torch.cuda.is_available() else "cpu"
model_name = "t5-base"

tokenizer = T5Tokenizer.from_pretrained(model_name)
model = T5ForConditionalGeneration.from_pretrained(model_name).to(device)

# Step 3: Summary Generation Function
def generate_summary(text):
    text = str(text).strip()
    if len(text) < 30:
        return ""

    input_text = "summarize: " + text
    inputs = tokenizer(input_text, return_tensors="pt", max_length=512, truncation=True).to(device)

    summary_ids = model.generate(
        **inputs,
        max_length=200,
        num_beams=4,
        early_stopping=True
    )

    return tokenizer.decode(summary_ids[0], skip_special_tokens=True)

In [27]:
# Step 4: Apply to first 1000 rows
tqdm.pandas()
subset_df['generated_summary'] = subset_df['text'].progress_apply(generate_summary)
subset_df.head(3)

100%|██████████| 1000/1000 [22:16<00:00,  1.34s/it]

          note_id  subject_id   hadm_id note_type  note_seq  \
0  10000032-DS-21    10000032  22595853        DS        21
1  10000032-DS-22    10000032  22841357        DS        22
2  10000032-DS-23    10000032  29079034        DS        23

             charttime            storetime  \
0  2180-05-07 00:00:00  2180-05-09 15:26:00
1  2180-06-27 00:00:00  2180-07-01 10:15:00
2  2180-07-25 00:00:00  2180-07-25 21:42:00

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           text  \

In [28]:
# Step 5: Match with MIMIC using note_id
merged_df = subset_df.merge(mimic_df[['note_id', 'target']], on='note_id', how='inner')

# Step 6: Filter only where generated_summary is not empty
eval_df = merged_df[merged_df['generated_summary'].str.strip().astype(bool)]

In [29]:
!pip install rouge_score

Collecting rouge_score
  Downloading rouge_score-0.1.2.tar.gz (17 kB)
  Preparing metadata (setup.py) ... done
Requirement already satisfied: absl-py in /usr/local/lib/python3.11/dist-packages (from rouge_score) (1.4.0)
Requirement already satisfied: nltk in /usr/local/lib/python3.11/dist-packages (from rouge_score) (3.9.1)
Requirement already satisfied: numpy in /usr/local/lib/python3.11/dist-packages (from rouge_score) (2.0.2)
Requirement already satisfied: six>=1.14.0 in /usr/local/lib/python3.11/dist-packages (from rouge_score) (1.17.0)
Requirement already satisfied: click in /usr/local/lib/python3.11/dist-packages (from nltk->rouge_score) (8.1.8)
Requirement already satisfied: joblib in /usr/local/lib/python3.11/dist-packages (from nltk->rouge_score) (1.4.2)
Requirement already satisfied: regex>=2021.8.3 in /usr/local/lib/python3.11/dist-packages (from nltk->rouge_score) (2024.11.6)
Requirement already satisfied: tqdm in /usr/local/lib/python3.11/dist-packages (from nltk->rouge_score) (4.67.1)
Building wheels for collected packages: rouge_score
  Building wheel for rouge_score (setup.py) ... done
  Created wheel for rouge_score: filename=rouge_score-0.1.2-py3-none-any.whl size=24934 sha256=ec98b671eff719dd32d0e6ac24199b1f9655c08ecedafdd1666055db2b63da78
  Stored in directory: /root/.cache/pip/wheels/1e/19/43/8a442dc83660ca25e163e1bd1f89919284ab0d0c1475475148
Successfully built rouge_score
Installing collected packages: rouge_score
Successfully installed rouge_score-0.1.2

In [30]:
# Step 7: Evaluate Metrics
import evaluate
from bert_score import score as bert_score

# ROUGE
rouge = evaluate.load("rouge")
rouge_result = rouge.compute(
    predictions=eval_df['generated_summary'].tolist(),
    references=eval_df['target'].tolist()
)

# BLEU
bleu = evaluate.load("bleu")
bleu_result = bleu.compute(
    predictions=eval_df['generated_summary'].tolist(),
    references=[[ref] for ref in eval_df['target'].tolist()]
)

# BERTScore
P, R, F1 = bert_score(
    eval_df['generated_summary'].tolist(),
    eval_df['target'].tolist(),
    lang='en'
)

bertscore_result = {
    "precision": P.mean().item(),
    "recall": R.mean().item(),
    "f1": F1.mean().item()
}

Downloading builder script:   0%|          | 0.00/6.27k [00:00<?, ?B/s]

Downloading builder script:   0%|          | 0.00/5.94k [00:00<?, ?B/s]

Downloading extra modules:   0%|          | 0.00/1.55k [00:00<?, ?B/s]

Downloading extra modules:   0%|          | 0.00/3.34k [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/25.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/482 [00:00<?, ?B/s]

vocab.json:   0%|          | 0.00/899k [00:00<?, ?B/s]

merges.txt:   0%|          | 0.00/456k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/1.36M [00:00<?, ?B/s]

Xet Storage is enabled for this repo, but the 'hf_xet' package is not installed. Falling back to regular HTTP download. For better performance, install the package with: `pip install huggingface_hub[hf_xet]` or `pip install hf_xet`
WARNING:huggingface_hub.file_download:Xet Storage is enabled for this repo, but the 'hf_xet' package is not installed. Falling back to regular HTTP download. For better performance, install the package with: `pip install huggingface_hub[hf_xet]` or `pip install hf_xet`

model.safetensors:   0%|          | 0.00/1.42G [00:00<?, ?B/s]

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['pooler.dense.bias', 'pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

In [31]:
# Step 8: Display Scores
print("Number of rows evaluated:", len(eval_df))
print("ROUGE:", rouge_result)
print("BLEU:", bleu_result)
print("BERTScore:", bertscore_result)

Number of rows evaluated: 819
ROUGE: {'rouge1': np.float64(0.09519244511238645), 'rouge2': np.float64(0.028151832873676612), 'rougeL': np.float64(0.06936576020863697), 'rougeLsum': np.float64(0.06936515131630819)}
BLEU: {'bleu': 6.87569790025609e-07, 'precisions': [0.5129861982434128, 0.12736228711245615, 0.06018120494676278, 0.04078442035142576], 'brevity_penalty': 6.11000211949018e-06, 'length_ratio': 0.07689005301265261, 'translation_length': 31880, 'reference_length': 414618}
BERTScore: {'precision': 0.8366767764091492, 'recall': 0.7773444056510925, 'f1': 0.8057137131690979}